server:
  port: 8888

spring:
  data:
    elasticsearch:
      cluster-name: es-mongodb
      cluster-nodes:  127.0.0.1:9300
logging:
  home: logs
  maxHistory: 30
  totalSizeCap: 20GB
  maxFileSize: 200MB
  config: classpath:logback-custom.xml
