server:
  port: 9063

spring:
  profiles:
    active: dev
  application:
    name: gateway
  cloud:
    #Nacos Server 的地址
    nacos:
      discovery:
        server-addr: 192.168.9.223:8848  #Nacos server 的地址
        namespace: zmm9023
      config:
        server-addr: 192.168.9.223:8848 #Nacos作为配置中心地址
        namespace: zmm9023
#以下配置信息并不是默认配置，而是我们自定义的配置，目的是不在 Controller 内硬编码服务提供者的服务名
#com.zmm.service-url:
#  nacos-user-com.zmm.service: http://spring-cloud-alibaba-nacos-provider #服务提供者的服务名


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  home: logs
  maxHistory: 30
  totalSizeCap: 20GB
  maxFileSize: 200MB
  config: classpath:logback-custom.xml

