server:
  port: 9064

spring:
  application:
    name: facade-9064
  profiles:
    active: dev
  #Nacos Server 的地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.9.223:8848  #Nacos server 的地址
        namespace: zmm9023
      config:
        server-addr: 192.168.9.223:8848 #Nacos作为配置中心地址
        namespace: zmm9023

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  home: logs
  maxHistory: 30
  totalSizeCap: 20GB
  maxFileSize: 200MB
  config: classpath:logback-custom.xml

