server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        #acknowledge-mode: AUTO
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
        #acknowledge-mode: AUTO


logging:
  home: logs
  maxHistory: 30
  totalSizeCap: 20GB
  maxFileSize: 200MB
  config: classpath:logback-custom.xml
