server:
  port: 8888



logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error

  home: logs
  maxHistory: 30
  totalSizeCap: 20GB
  maxFileSize: 200MB
  config: classpath:logback-custom.xml
