server:
  port: 8888

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /

springfox:
  documentation:
    swagger:
      use-model-v3: false

logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error

  home: logs
  maxHistory: 30
  totalSizeCap: 20GB
  maxFileSize: 200MB
  config: classpath:logback-custom.xml
