server:
  port: 8888

spring:
  data:
    elasticsearch:
      cluster-name: es-mongodb
      cluster-nodes:  127.0.0.1:9200
      index:
        number-of-replicas: 0
        number-of-shards: 3
logging:
  home: logs
  maxHistory: 30
  totalSizeCap: 20GB
  maxFileSize: 200MB
  config: classpath:logback-custom.xml
