server:
  port: 8888

spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

logging:
  home: logs
  maxHistory: 30
  totalSizeCap: 20GB
  maxFileSize: 200MB
  config: classpath:logback-custom.xml
